### ISSUE TITLE
CPU-GPU copies instead of GPU-GPU MPI communications in cg_mpi ?

### ISSUE THREAD

**Issue by jdechard** [ROCmSoftwarePlatform/rocALUTION#161]
Hello,

I am using the **cg_mpi.ccp** sample from rocALUTION to test GPU-GPU MPI communications.

When running **cg_mpi** with 2 MPI tasks and 1 GPU per task on a AMD MI250X node (with Trento CPU) I can see 2 arrays transfered from GPU to CPU (green) and back (purple) for each solver iteration step (see rocprof profiling below). Note that I modified the source code with `ls.InitMinIter(10);`.

![rocprof_cg_mpi](https://user-images.githubusercontent.com/54707227/214642627-ed7bc9e3-dda7-497c-af4e-acbf29d023dd.jpg)

By exporting `ROCALUTION_LAYER=1`, I can see that the data sizes correspond to the ghost cells. I assume that an MPI communication is then done to update gost cell values.

I was expecting to avoid this GPU-CPU ping pong since the MI250X node has everything needed (hardware + software stacks) to perform GPU to GPU MPI communications. Does rocALUTION MPI calls support GPU device addresses ? Or am I missing something here ?

The same pattern is observed on our application and we would like to understand (and if possible avoid) these costly data exchange.

Feel free to ask me any details if needed.

Thank you in advance.

**Comment by ntrost57** [comment]
Currently, rocALUTION does not support direct GPU-GPU communication. This is something we will be adding in a future release, however.

**Comment by jdechard** [comment]
Thanks for you quick answer.
Do you have an idea of when this feature will be supported ?

**Comment by ntrost57** [comment]
I am not able to give you a specific release. May I ask why you are interested in such feature? I do not expect any performance improvement on most solvers, as time critical algorithms such as SpMV can fully hide communication by computation.

**Comment by jdechard** [comment]
I understand your point but the bench case we are working on shows that about 10% of the time of each rocALUTION solver call (1 per time step) is dedicated to hipMemcpy for these ghost cells exchange, with almost no computational kernels overlap. We use the CG solver with the c-amg preconditionner. It would have been nice to try this feature on AMD nodes specifically designed to do so. We will test it when it will be available :).

**Comment by ntrost57** [comment]
There is going to be a change soon, which will introduce multiple streams in order to overlap packing and sending with the interior computation. If you are using MPI, I guess you compile from source. I'll update this issue, once that change has been implemented, so you can re do your performance tests.

**Comment by jdechard** [comment]
Sounds a good feature to try, thanks !

**Comment by ntrost57** [comment]
I have merged some major modifications to `GlobalMatrix::Apply()` in order to overlap communication and packing with interior matrix vector multiplication. This should slightly improve SpMV performance and scale linear with additional nodes / GPUs. Let me know, if this fixes the issue you have been observing.
Note, that you will have to checkout `develop` branch, in order to see those changes.
