### ISSUE TITLE
Problem with distribute_matrix in common.hpp

### ISSUE THREAD

**Issue by pelyakim** [ROCmSoftwarePlatform/rocALUTION#164]
Hello, 

I have a problem with the distribute_matrix function (in common.hpp) that I integrated in my code (JADIM  - issue rocALUTION for fortran #163 ) to be able to use rocALUTION on several mpi processes with 1 graphics card for the moment. 
The function works for 1 mpi process but with 2 mpi processes, I have a segfault that appears as soon as the 1st mpi process arrives gmat->SetParallelManager(*pm); 
I have made many printouts and I find that there are some things a bit strange. 
Can you advise me to solve this bug ? Thanks for your help. Pierre

**Comment by ntrost57** [comment]
The `distribute_matrix()` is just an example and might need major modifications to work with your code. Also keep in mind that the decomposition done by this example is very simple and most likely not optimal for your specific use case.
I guess I need some more details, in order to see if there is an issue with rocalution. Can you successfully run mpi examples, that are using `distribute_matrix()` functionality?

**Comment by doctorcolinsmith** [comment]
Closing this out as the reporter has not followed up.
